/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package git.enigmaneering.org/mental/capi */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "capi.go"

#include <stdlib.h>
#include <stdint.h>
#include <string.h>

// Opaque handle types
typedef void* MentalDevice;
typedef void* MentalReference;
typedef void* MentalKernel;

// Device info structure
typedef struct {
    int index;
    char* name;
    int device_type;  // 0=Other, 1=Integrated, 2=Discrete, 3=Virtual
    int api;          // 0=Metal, 1=Vulkan, 2=D3D12, 3=OpenCL
} MentalDeviceInfo;

// Error codes
typedef enum {
    MENTAL_OK = 0,
    MENTAL_ERROR_INVALID_HANDLE = -1,
    MENTAL_ERROR_ALLOCATION_FAILED = -2,
    MENTAL_ERROR_COMPILATION_FAILED = -3,
    MENTAL_ERROR_DISPATCH_FAILED = -4,
    MENTAL_ERROR_INVALID_SIZE = -5,
    MENTAL_ERROR_DEVICE_NOT_FOUND = -6,
} MentalError;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern int mental_init(void);
extern int mental_get_device_count(void);
extern int mental_get_device_info(int index, MentalDeviceInfo* info);
extern void mental_free_device_info(MentalDeviceInfo* info);
extern MentalReference mental_create_reference(size_t size, int device_index);
extern MentalReference mental_create_reference_from_data(uint8_t* data, size_t size, int device_index);
extern int mental_reference_read(MentalReference handle, uint8_t* buffer, size_t size);
extern int mental_reference_write(MentalReference handle, uint8_t* data, size_t size);
extern size_t mental_reference_size(MentalReference handle);
extern int mental_release_reference(MentalReference handle);
extern MentalKernel mental_compile_kernel(char* source, int device_index);
extern int mental_kernel_dispatch(MentalKernel kernel_handle, MentalReference* input_handles, int input_count, MentalReference output_handle, int work_size);
extern int mental_release_kernel(MentalKernel handle);

#ifdef __cplusplus
}
#endif
